### ISSUE TITLE
关于Post版的文件包含漏洞

### ISSUE THREAD

**Issue by BackTrackCRoot** [Chora10/Cknife#15]
不知道是不是我不太会用C刀的配置文件还在怎么--
遇到一个文件包含漏洞，是post版的，需要post一段数据
才能引用日志中的一句话
好像C刀仅仅支持get版本
能否加入一下连接之前post数据？

**Comment by Chora10** [comment]
这个功能不太实用，建议写一个中专脚本模拟POST，然后Cknife连接该中专脚本。

**Comment by BackTrackCRoot** [comment]
多谢 ，哈哈，已写。我也想到了这个。
