### ISSUE TITLE
关于大文件上传问题

### ISSUE THREAD

**Issue by wangeradd1** [Chora10/Cknife#29]
release 1.0版本

1、遇到一个情况，php环境，shell是普通php一句话，一个5MB的文件上传失败；
2、同样的php环境，新建大的文本文件也同样失败。

希望作者早日修复这个bug。

**Comment by Chora10** [comment]
谢谢亲的反馈,麻烦请告知版本以及系统,发布前做过测试,是可以正常上传5MB以上的文件的.
