### ISSUE TITLE
连接不上

### ISSUE THREAD

**Issue by 1eafy** [Chora10/Cknife#54]
![Snipaste_2019-05-12_01-19-32](https://user-images.githubusercontent.com/39360558/57572972-57c34280-7454-11e9-8570-d53d25483498.png)
![Snipaste_2019-05-12_01-19-49](https://user-images.githubusercontent.com/39360558/57572974-585bd900-7454-11e9-9b5a-240d07b3dc87.png)
连接不上，报错了，这个是从作者仓库git下来用eclipse打包的jar

**Comment by jcpyang** [comment]
![Snipaste_2019-05-12_01-25-57](https://user-images.githubusercontent.com/39360558/57573026-e9cb4b00-7454-11e9-8eef-66754ad559e1.png)

**Comment by 1eafy** [comment]
![Snipaste_2019-05-12_01-49-25](https://user-images.githubusercontent.com/39360558/57573320-880ce000-7458-11e9-9f24-2a381161a6e0.png)
这个是从网上下载的Cknife，同样报错，但报错信息不同，是我的Java版本问题吗？？

**Comment by ViCrack** [comment]
1.7

**Comment by 1eafy** [comment]
> 1.7

换了1.8 ，自己打包的仍然出现貌似Base64编码的错误
![image](https://user-images.githubusercontent.com/39360558/57577466-f9c14a00-74a9-11e9-8975-28cbe115a355.png)

**Comment by 1eafy** [comment]
网上下载无报错（应该是我打包出问题了），但是连接失败了，
![image](https://user-images.githubusercontent.com/39360558/57577499-eb276280-74aa-11e9-9174-a81ca2bf7078.png)

我用了蚁剑也测试连接失败了，显示返回为空
![Snipaste_2019-05-12_11-40-14](https://user-images.githubusercontent.com/39360558/57577498-d34fde80-74aa-11e9-8c66-d6ab15e68e7d.png)

**Comment by ViCrack** [comment]
BASE64Encoder早已是过时的api，用1.8的话可以把它换成java.util.base64

连接失败的问题你用蚁剑设置抓包看下，就这点图看不出啥
